max-players: 4
lobby:
  world-name: dbm-lobby-world
  spawn-location: [0.0, 6.0, 0.0]
  spawn-rotation: [-166.0, 3.0]
  npcs:
    enabled: true
    locations:
      - [4.5, 5.0, -11.5]
      - [7.5, 5.0, -9.5]
      - [11.5, 5.0, -10.5]
      - [13.5, 5.0, -8.5]
game:
  world-name: dbm-game-world
default-world:
  name: dead-by-minecraft-development